include:
#  - include/redis.yaml
#  - include/manticore.yaml
# ...other services

services:
  server:
    env_file: .env
    container_name: pydev
    volumes:
      - ./$PROJECT:/home/$USER/$PROJECT
      - ./data/.bash_history:/home/$USER/.bash_history
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER_ID: $UID
        USER_NAME: $USER
        PYTHON_VERSION: $PYTHON_VERSION
        IMAGE: $IMAGE
        PROJECT: $PROJECT
    ports:
      - 8000:8000
      - 5678:5678
 #   depends_on:
 #     - redis
 #     ...
# TODO db rabbitmq celery frontend
