#include:
#  - include/postgresql.yaml
#  - include/redis.yaml
#  - include/manticore.yaml
# ...other services
name: django-helloworld
services:
  devcontainer:
    command: $CMD # bash # sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    container_name: dockerenv
    volumes:
      - ../:/workspace
      - ~/tmp/data/.bash_history:/home/$USER/.bash_history
    build:
      context: ../
      dockerfile: ./dockerenv/Dockerfile
      args:
        USER_ID: $UID
        USER_NAME: $USER
        PYTHON_VERSION: $PYTHON_VERSION
        IMAGE: $IMAGE
        BUILD_SH: $BUILD_SH
    stdin_open: true # docker run -i
    tty: true # docker run -t
    ports:
      - 8000:8000
      - 5678:5678
#    depends_on:
#      - postgresql
 #     - redis
 #     ...
# TODO db rabbitmq celery frontend monitoring
