include:
#  - include/redis.yaml
#  - include/manticore.yaml
# ...other services

services:
  server:
    env_file: .env
    container_name: dockerenv
    volumes:
      - ../:/home/$USER/src
      - ../dockerenv/data/.bash_history:/home/$USER/.bash_history
    build:
      context: ../.
      dockerfile: ./dockerenv/Dockerfile
      args:
        USER_ID: $UID
        USER_NAME: $USER
        PYTHON_VERSION: $PYTHON_VERSION
        IMAGE: $IMAGE
        BUILD_ROOT_SH: $BUILD_ROOT_SH
        BUILD_USER_SH: $BUILD_USER_SH
    ports:
      - 8000:8000
      - 5678:5678
 #   depends_on:
 #     - redis
 #     ...
# TODO db rabbitmq celery frontend
