FROM python:3.11.10-bullseye AS builder
WORKDIR /usr/src/app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
#COPY requirements.txt ./

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

#ENV .env
#EXPOSE 8080
FROM python:3.11.10-bullseye
COPY --from=builder /opt/venv /opt/venv
WORKDIR /usr/src/app
COPY . .
ENV PATH="/opt/venv/bin:$PATH"
CMD [ "python", "./main.py" ]
