services:
  postgresql:
    container_name: postgresql
    image: postgres # docker.io/library/postgres for podman
    restart: always
    volumes:
      - ~/tmp/data/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD = trust
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 8082:5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest # docker.io/dpage/pgadmin4:latest for podman
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: no@no.no
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DISABLE_POSTFIX: yes
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 80

    ports:
      - 8081:80
